### ISSUE TITLE
Rest api is not mentioned on https://www.dropbox.com/developers/apps

### ISSUE THREAD

**Issue by MichaKersloot** [jwagner12345/DropboxZimlet#3]
Hi,

maybe you should update the documentation to refer to request for an 'App folder' API key and secret at dropbox instead of an REST API.

**Comment by jwagner12345** [comment]
@MichaKersloot Do you want to send a pull request for the suggested changes?

**Comment by MichaKersloot** [comment]
It looks like I've managed to create such a request.
